# Generated by Django 5.1.7 on 2026-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('corrected_text', models.TextField(blank=True, default='')),
                ('check_type', models.CharField(choices=[('grammar', 'Grammar Check'), ('spelling', 'Spelling Check'), ('clarity', 'Clarity Improvement'), ('readability', 'Readability Analysis'), ('full', 'Full Check')], max_length=20)),
                ('errors_found', models.IntegerField(default=0)),
                ('corrections', models.JSONField(blank=True, default=list)),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Check Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
